import type { NextPage } from "next";
import Head from "next/head";

const AdminDashboard: NextPage = () => {

  if(global.window.localStorage.getItem("index")){
    global.window.location.href = "/admin/login"
  }

  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>

      </section>
    </div>
  );
};

export default AdminDashboard;